name: Build

on: [push, pull_request]

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:

  variables:
    runs-on: ubuntu-latest
    steps:
      - name: Load and set variables
        run: |
          GOVERSION=$(cat $GITHUB_WORKSPACE/GO_VERSION)
          echo "GOVERSION=$GOVERSION" >> $GITHUB_ENV
    
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GOVERSION }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.56

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.19', '1.20', '1.21']
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go version
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Run go test
        run:  make test

